# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loadMeasurements.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_loadMeasurementDialog(object):
    def setupUi(self, loadMeasurementDialog):
        loadMeasurementDialog.setObjectName("loadMeasurementDialog")
        loadMeasurementDialog.resize(482, 377)
        loadMeasurementDialog.setModal(True)
        self.gridLayout = QtWidgets.QGridLayout(loadMeasurementDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonBox = QtWidgets.QDialogButtonBox(loadMeasurementDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close|QtWidgets.QDialogButtonBox.Open)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 5, 0, 1, 1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(loadMeasurementDialog)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.fileType = QtWidgets.QComboBox(loadMeasurementDialog)
        self.fileType.setObjectName("fileType")
        self.fileType.addItem("")
        self.fileType.addItem("")
        self.fileType.addItem("")
        self.fileType.addItem("")
        self.fileType.addItem("")
        self.fileType.addItem("")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.fileType)
        self.fsLabel = QtWidgets.QLabel(loadMeasurementDialog)
        self.fsLabel.setObjectName("fsLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.fsLabel)
        self.fs = QtWidgets.QComboBox(loadMeasurementDialog)
        self.fs.setObjectName("fs")
        self.fs.addItem("")
        self.fs.addItem("")
        self.fs.addItem("")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.fs)
        self.gridLayout.addLayout(self.formLayout, 0, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.loadedFiles = QtWidgets.QPlainTextEdit(loadMeasurementDialog)
        self.loadedFiles.setEnabled(False)
        self.loadedFiles.setReadOnly(True)
        self.loadedFiles.setObjectName("loadedFiles")
        self.gridLayout_2.addWidget(self.loadedFiles, 1, 0, 1, 1)
        self.ignoredFiles = QtWidgets.QPlainTextEdit(loadMeasurementDialog)
        self.ignoredFiles.setEnabled(False)
        self.ignoredFiles.setObjectName("ignoredFiles")
        self.gridLayout_2.addWidget(self.ignoredFiles, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(loadMeasurementDialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setFrameShape(QtWidgets.QFrame.Box)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(loadMeasurementDialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setFrameShape(QtWidgets.QFrame.Box)
        self.label_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 1, 0, 1, 1)

        self.retranslateUi(loadMeasurementDialog)
        self.buttonBox.accepted.connect(loadMeasurementDialog.accept)
        self.buttonBox.rejected.connect(loadMeasurementDialog.reject)
        self.fileType.currentIndexChanged['QString'].connect(loadMeasurementDialog.fileTypeChanged)
        QtCore.QMetaObject.connectSlotsByName(loadMeasurementDialog)

    def retranslateUi(self, loadMeasurementDialog):
        _translate = QtCore.QCoreApplication.translate
        loadMeasurementDialog.setWindowTitle(_translate("loadMeasurementDialog", "Load Measurements"))
        self.label_2.setText(_translate("loadMeasurementDialog", "File Type"))
        self.fileType.setItemText(0, _translate("loadMeasurementDialog", "txt"))
        self.fileType.setItemText(1, _translate("loadMeasurementDialog", "dbl"))
        self.fileType.setItemText(2, _translate("loadMeasurementDialog", "wav"))
        self.fileType.setItemText(3, _translate("loadMeasurementDialog", "HolmImpulse"))
        self.fileType.setItemText(4, _translate("loadMeasurementDialog", "REW"))
        self.fileType.setItemText(5, _translate("loadMeasurementDialog", "ARTA"))
        self.fsLabel.setText(_translate("loadMeasurementDialog", "Fs"))
        self.fs.setCurrentText(_translate("loadMeasurementDialog", "44100"))
        self.fs.setItemText(0, _translate("loadMeasurementDialog", "44100"))
        self.fs.setItemText(1, _translate("loadMeasurementDialog", "48000"))
        self.fs.setItemText(2, _translate("loadMeasurementDialog", "96000"))
        self.label.setText(_translate("loadMeasurementDialog", "Loaded Measurements"))
        self.label_3.setText(_translate("loadMeasurementDialog", "Ignored Files"))

