# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pypolarmap.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1638, 793)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.graphTabs = QtWidgets.QTabWidget(self.centralwidget)
        self.graphTabs.setEnabled(False)
        self.graphTabs.setMinimumSize(QtCore.QSize(0, 0))
        self.graphTabs.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.graphTabs.setObjectName("graphTabs")
        self.impulseTab = QtWidgets.QWidget()
        self.impulseTab.setObjectName("impulseTab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.impulseTab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.graphLayout = QtWidgets.QGridLayout()
        self.graphLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.graphLayout.setObjectName("graphLayout")
        self.impulseGraph = MplWidget(self.impulseTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(9)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.impulseGraph.sizePolicy().hasHeightForWidth())
        self.impulseGraph.setSizePolicy(sizePolicy)
        self.impulseGraph.setMinimumSize(QtCore.QSize(600, 400))
        self.impulseGraph.setObjectName("impulseGraph")
        self.graphLayout.addWidget(self.impulseGraph, 0, 1, 1, 8)
        self.impulseControlsContainer = QtWidgets.QVBoxLayout()
        self.impulseControlsContainer.setObjectName("impulseControlsContainer")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.measurementsHeaderLabel = QtWidgets.QLabel(self.impulseTab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.measurementsHeaderLabel.setFont(font)
        self.measurementsHeaderLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.measurementsHeaderLabel.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.measurementsHeaderLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.measurementsHeaderLabel.setObjectName("measurementsHeaderLabel")
        self.verticalLayout.addWidget(self.measurementsHeaderLabel)
        self.measurementDetailsLayout = QtWidgets.QFormLayout()
        self.measurementDetailsLayout.setObjectName("measurementDetailsLayout")
        self.fsLabel = QtWidgets.QLabel(self.impulseTab)
        self.fsLabel.setObjectName("fsLabel")
        self.measurementDetailsLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.fsLabel)
        self.fs = QtWidgets.QSpinBox(self.impulseTab)
        self.fs.setEnabled(False)
        self.fs.setMinimum(44100)
        self.fs.setMaximum(384000)
        self.fs.setSingleStep(100)
        self.fs.setProperty("value", 48000)
        self.fs.setDisplayIntegerBase(10)
        self.fs.setObjectName("fs")
        self.measurementDetailsLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.fs)
        self.dataPath = QtWidgets.QLineEdit(self.impulseTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dataPath.sizePolicy().hasHeightForWidth())
        self.dataPath.setSizePolicy(sizePolicy)
        self.dataPath.setMaximumSize(QtCore.QSize(320, 16777215))
        self.dataPath.setObjectName("dataPath")
        self.measurementDetailsLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.dataPath)
        self.verticalLayout.addLayout(self.measurementDetailsLayout)
        self.measurementView = QtWidgets.QListView(self.impulseTab)
        self.measurementView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.measurementView.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.measurementView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.measurementView.setObjectName("measurementView")
        self.verticalLayout.addWidget(self.measurementView)
        self.removeWindowBtn = QtWidgets.QPushButton(self.impulseTab)
        self.removeWindowBtn.setEnabled(False)
        self.removeWindowBtn.setCheckable(True)
        self.removeWindowBtn.setFlat(False)
        self.removeWindowBtn.setObjectName("removeWindowBtn")
        self.verticalLayout.addWidget(self.removeWindowBtn)
        self.applyWindowBtn = QtWidgets.QPushButton(self.impulseTab)
        self.applyWindowBtn.setEnabled(False)
        self.applyWindowBtn.setObjectName("applyWindowBtn")
        self.verticalLayout.addWidget(self.applyWindowBtn)
        self.impulseControlsContainer.addLayout(self.verticalLayout)
        self.windowControlContainer = QtWidgets.QGridLayout()
        self.windowControlContainer.setObjectName("windowControlContainer")
        self.leftWindowSample = QtWidgets.QSpinBox(self.impulseTab)
        self.leftWindowSample.setObjectName("leftWindowSample")
        self.windowControlContainer.addWidget(self.leftWindowSample, 1, 2, 1, 1)
        self.rightWindowType = QtWidgets.QComboBox(self.impulseTab)
        self.rightWindowType.setObjectName("rightWindowType")
        self.rightWindowType.addItem("")
        self.rightWindowType.addItem("")
        self.rightWindowType.addItem("")
        self.rightWindowType.addItem("")
        self.rightWindowType.addItem("")
        self.rightWindowType.addItem("")
        self.windowControlContainer.addWidget(self.rightWindowType, 2, 1, 1, 2)
        self.leftWindowPercent = QtWidgets.QSpinBox(self.impulseTab)
        self.leftWindowPercent.setMinimum(12)
        self.leftWindowPercent.setMaximum(75)
        self.leftWindowPercent.setProperty("value", 50)
        self.leftWindowPercent.setObjectName("leftWindowPercent")
        self.windowControlContainer.addWidget(self.leftWindowPercent, 1, 1, 1, 1)
        self.rightWindowPercent = QtWidgets.QSpinBox(self.impulseTab)
        self.rightWindowPercent.setMinimum(12)
        self.rightWindowPercent.setMaximum(75)
        self.rightWindowPercent.setProperty("value", 50)
        self.rightWindowPercent.setObjectName("rightWindowPercent")
        self.windowControlContainer.addWidget(self.rightWindowPercent, 3, 1, 1, 1)
        self.rightWindowSample = QtWidgets.QSpinBox(self.impulseTab)
        self.rightWindowSample.setObjectName("rightWindowSample")
        self.windowControlContainer.addWidget(self.rightWindowSample, 3, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.impulseTab)
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.windowControlContainer.addWidget(self.label, 0, 0, 2, 1)
        self.label_2 = QtWidgets.QLabel(self.impulseTab)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.windowControlContainer.addWidget(self.label_2, 2, 0, 2, 1)
        self.leftWindowType = QtWidgets.QComboBox(self.impulseTab)
        self.leftWindowType.setIconSize(QtCore.QSize(24, 24))
        self.leftWindowType.setObjectName("leftWindowType")
        self.leftWindowType.addItem("")
        self.leftWindowType.addItem("")
        self.leftWindowType.addItem("")
        self.leftWindowType.addItem("")
        self.leftWindowType.addItem("")
        self.leftWindowType.addItem("")
        self.windowControlContainer.addWidget(self.leftWindowType, 0, 1, 1, 2)
        self.impulseControlsContainer.addLayout(self.windowControlContainer)
        self.findPeakButton = QtWidgets.QPushButton(self.impulseTab)
        self.findPeakButton.setObjectName("findPeakButton")
        self.impulseControlsContainer.addWidget(self.findPeakButton)
        self.zoomOutBtn = QtWidgets.QPushButton(self.impulseTab)
        self.zoomOutBtn.setObjectName("zoomOutBtn")
        self.impulseControlsContainer.addWidget(self.zoomOutBtn)
        self.zoomInButton = QtWidgets.QPushButton(self.impulseTab)
        self.zoomInButton.setObjectName("zoomInButton")
        self.impulseControlsContainer.addWidget(self.zoomInButton)
        self.graphLayout.addLayout(self.impulseControlsContainer, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.graphLayout, 0, 0, 1, 1)
        self.graphTabs.addTab(self.impulseTab, "")
        self.measuredMagnitudeTab = QtWidgets.QWidget()
        self.measuredMagnitudeTab.setObjectName("measuredMagnitudeTab")
        self.measuredMagnitudeGridLayout = QtWidgets.QGridLayout(self.measuredMagnitudeTab)
        self.measuredMagnitudeGridLayout.setObjectName("measuredMagnitudeGridLayout")
        self.measuredMagnitudeControlLayout = QtWidgets.QGridLayout()
        self.measuredMagnitudeControlLayout.setObjectName("measuredMagnitudeControlLayout")
        self.selectAllMeasuredButton = QtWidgets.QPushButton(self.measuredMagnitudeTab)
        self.selectAllMeasuredButton.setObjectName("selectAllMeasuredButton")
        self.measuredMagnitudeControlLayout.addWidget(self.selectAllMeasuredButton, 1, 0, 1, 1)
        self.clearAllMeasuredButton = QtWidgets.QPushButton(self.measuredMagnitudeTab)
        self.clearAllMeasuredButton.setObjectName("clearAllMeasuredButton")
        self.measuredMagnitudeControlLayout.addWidget(self.clearAllMeasuredButton, 1, 1, 1, 1)
        self.measuredMagnitudeCurves = QtWidgets.QListWidget(self.measuredMagnitudeTab)
        self.measuredMagnitudeCurves.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.measuredMagnitudeCurves.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.measuredMagnitudeCurves.setObjectName("measuredMagnitudeCurves")
        self.measuredMagnitudeControlLayout.addWidget(self.measuredMagnitudeCurves, 2, 0, 1, 2)
        self.measuredMagnitudeCurvesLabel = QtWidgets.QLabel(self.measuredMagnitudeTab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.measuredMagnitudeCurvesLabel.setFont(font)
        self.measuredMagnitudeCurvesLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.measuredMagnitudeCurvesLabel.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.measuredMagnitudeCurvesLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.measuredMagnitudeCurvesLabel.setObjectName("measuredMagnitudeCurvesLabel")
        self.measuredMagnitudeControlLayout.addWidget(self.measuredMagnitudeCurvesLabel, 0, 0, 1, 2)
        self.measuredMagnitudeGridLayout.addLayout(self.measuredMagnitudeControlLayout, 0, 0, 1, 1)
        self.measuredMagnitudeGraph = MplWidget(self.measuredMagnitudeTab)
        self.measuredMagnitudeGraph.setMinimumSize(QtCore.QSize(847, 400))
        self.measuredMagnitudeGraph.setObjectName("measuredMagnitudeGraph")
        self.measuredMagnitudeGridLayout.addWidget(self.measuredMagnitudeGraph, 0, 1, 1, 1)
        self.measuredMagnitudeGridLayout.setColumnStretch(1, 1)
        self.graphTabs.addTab(self.measuredMagnitudeTab, "")
        self.measuredPolarTab = QtWidgets.QWidget()
        self.measuredPolarTab.setObjectName("measuredPolarTab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.measuredPolarTab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.measuredPolarGraph = MplWidget(self.measuredPolarTab)
        self.measuredPolarGraph.setMinimumSize(QtCore.QSize(847, 400))
        self.measuredPolarGraph.setObjectName("measuredPolarGraph")
        self.gridLayout_4.addWidget(self.measuredPolarGraph, 0, 0, 1, 1)
        self.graphTabs.addTab(self.measuredPolarTab, "")
        self.measuredMultiTab = QtWidgets.QWidget()
        self.measuredMultiTab.setObjectName("measuredMultiTab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.measuredMultiTab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.measuredMultiGraph = MplWidget(self.measuredMultiTab)
        self.measuredMultiGraph.setMinimumSize(QtCore.QSize(847, 400))
        self.measuredMultiGraph.setObjectName("measuredMultiGraph")
        self.gridLayout_5.addWidget(self.measuredMultiGraph, 0, 0, 1, 1)
        self.graphTabs.addTab(self.measuredMultiTab, "")
        self.modalParametersTab = QtWidgets.QWidget()
        self.modalParametersTab.setObjectName("modalParametersTab")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.modalParametersTab)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.modalParametersSelectorLayout = QtWidgets.QGridLayout()
        self.modalParametersSelectorLayout.setObjectName("modalParametersSelectorLayout")
        self.selectAllModalParametersButton = QtWidgets.QPushButton(self.modalParametersTab)
        self.selectAllModalParametersButton.setObjectName("selectAllModalParametersButton")
        self.modalParametersSelectorLayout.addWidget(self.selectAllModalParametersButton, 1, 0, 1, 1)
        self.clearAllModalParametersButton = QtWidgets.QPushButton(self.modalParametersTab)
        self.clearAllModalParametersButton.setObjectName("clearAllModalParametersButton")
        self.modalParametersSelectorLayout.addWidget(self.clearAllModalParametersButton, 1, 1, 1, 1)
        self.modesLabel = QtWidgets.QLabel(self.modalParametersTab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.modesLabel.setFont(font)
        self.modesLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.modesLabel.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.modesLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.modesLabel.setObjectName("modesLabel")
        self.modalParametersSelectorLayout.addWidget(self.modesLabel, 0, 0, 1, 2)
        self.modalParametersList = QtWidgets.QListWidget(self.modalParametersTab)
        self.modalParametersList.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.modalParametersList.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.modalParametersList.setObjectName("modalParametersList")
        self.modalParametersSelectorLayout.addWidget(self.modalParametersList, 2, 0, 1, 2)
        self.horizontalLayout.addLayout(self.modalParametersSelectorLayout)
        self.modalParametersGraph = MplWidget(self.modalParametersTab)
        self.modalParametersGraph.setObjectName("modalParametersGraph")
        self.horizontalLayout.addWidget(self.modalParametersGraph)
        self.horizontalLayout.setStretch(1, 1)
        self.graphTabs.addTab(self.modalParametersTab, "")
        self.modalPolarTab = QtWidgets.QWidget()
        self.modalPolarTab.setObjectName("modalPolarTab")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.modalPolarTab)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.modalPolarGraph = MplWidget(self.modalPolarTab)
        self.modalPolarGraph.setMinimumSize(QtCore.QSize(847, 400))
        self.modalPolarGraph.setObjectName("modalPolarGraph")
        self.gridLayout_6.addWidget(self.modalPolarGraph, 0, 0, 1, 1)
        self.graphTabs.addTab(self.modalPolarTab, "")
        self.modalMultiTab = QtWidgets.QWidget()
        self.modalMultiTab.setObjectName("modalMultiTab")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.modalMultiTab)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.modalMultiGraph = MplWidget(self.modalMultiTab)
        self.modalMultiGraph.setMinimumSize(QtCore.QSize(847, 400))
        self.modalMultiGraph.setObjectName("modalMultiGraph")
        self.gridLayout_7.addWidget(self.modalMultiGraph, 0, 0, 1, 1)
        self.graphTabs.addTab(self.modalMultiTab, "")
        self.gridLayout.addWidget(self.graphTabs, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1638, 31))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoad = QtWidgets.QAction(MainWindow)
        self.actionLoad.setObjectName("actionLoad")
        self.actionSave_Current_Image = QtWidgets.QAction(MainWindow)
        self.actionSave_Current_Image.setObjectName("actionSave_Current_Image")
        self.actionShow_Logs = QtWidgets.QAction(MainWindow)
        self.actionShow_Logs.setObjectName("actionShow_Logs")
        self.actionModal_Parameters = QtWidgets.QAction(MainWindow)
        self.actionModal_Parameters.setObjectName("actionModal_Parameters")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.action_Display = QtWidgets.QAction(MainWindow)
        self.action_Display.setObjectName("action_Display")
        self.menuFile.addAction(self.actionLoad)
        self.menuFile.addAction(self.actionSave_Current_Image)
        self.menuHelp.addAction(self.actionShow_Logs)
        self.menuHelp.addAction(self.actionAbout)
        self.menuSettings.addAction(self.actionModal_Parameters)
        self.menuSettings.addAction(self.action_Display)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.graphTabs.setCurrentIndex(0)
        self.zoomInButton.clicked.connect(MainWindow.zoomIn)
        self.removeWindowBtn.clicked.connect(MainWindow.removeWindow)
        self.graphTabs.currentChanged['int'].connect(MainWindow.onGraphTabChange)
        self.zoomOutBtn.clicked.connect(MainWindow.zoomOut)
        self.applyWindowBtn.clicked.connect(MainWindow.updateWindow)
        self.zoomOutBtn.clicked.connect(MainWindow.zoomOut)
        self.rightWindowSample.valueChanged['int'].connect(MainWindow.updateRightWindow)
        self.leftWindowSample.valueChanged['int'].connect(MainWindow.updateLeftWindow)
        self.leftWindowPercent.valueChanged['int'].connect(MainWindow.updateLeftWindow)
        self.leftWindowType.currentTextChanged['QString'].connect(MainWindow.updateLeftWindow)
        self.rightWindowType.currentTextChanged['QString'].connect(MainWindow.updateRightWindow)
        self.rightWindowPercent.valueChanged['int'].connect(MainWindow.updateRightWindow)
        self.findPeakButton.clicked.connect(MainWindow.findFirstPeak)
        self.selectAllModalParametersButton.clicked.connect(self.modalParametersList.selectAll)
        self.clearAllModalParametersButton.clicked.connect(self.modalParametersList.clearSelection)
        self.selectAllMeasuredButton.clicked.connect(self.measuredMagnitudeCurves.selectAll)
        self.clearAllMeasuredButton.clicked.connect(self.measuredMagnitudeCurves.clearSelection)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "pypolarmap"))
        self.measurementsHeaderLabel.setText(_translate("MainWindow", "Measurements"))
        self.fsLabel.setText(_translate("MainWindow", "Fs"))
        self.fs.setSuffix(_translate("MainWindow", "Hz"))
        self.removeWindowBtn.setText(_translate("MainWindow", "Remove Window"))
        self.applyWindowBtn.setText(_translate("MainWindow", "Apply Window"))
        self.rightWindowType.setItemText(0, _translate("MainWindow", "Rectangle"))
        self.rightWindowType.setItemText(1, _translate("MainWindow", "Tukey"))
        self.rightWindowType.setItemText(2, _translate("MainWindow", "Hann"))
        self.rightWindowType.setItemText(3, _translate("MainWindow", "Hamming"))
        self.rightWindowType.setItemText(4, _translate("MainWindow", "Blackman-Harris"))
        self.rightWindowType.setItemText(5, _translate("MainWindow", "Nuttall"))
        self.leftWindowPercent.setSuffix(_translate("MainWindow", "%"))
        self.rightWindowPercent.setSuffix(_translate("MainWindow", "%"))
        self.label.setText(_translate("MainWindow", "Left"))
        self.label_2.setText(_translate("MainWindow", "Right"))
        self.leftWindowType.setItemText(0, _translate("MainWindow", "Rectangle"))
        self.leftWindowType.setItemText(1, _translate("MainWindow", "Tukey"))
        self.leftWindowType.setItemText(2, _translate("MainWindow", "Hann"))
        self.leftWindowType.setItemText(3, _translate("MainWindow", "Hamming"))
        self.leftWindowType.setItemText(4, _translate("MainWindow", "Blackman-Harris"))
        self.leftWindowType.setItemText(5, _translate("MainWindow", "Nuttall"))
        self.findPeakButton.setText(_translate("MainWindow", "Find First Peak"))
        self.zoomOutBtn.setText(_translate("MainWindow", "Zoom Out"))
        self.zoomInButton.setText(_translate("MainWindow", "Zoom To Window"))
        self.graphTabs.setTabText(self.graphTabs.indexOf(self.impulseTab), _translate("MainWindow", "Impulse"))
        self.selectAllMeasuredButton.setText(_translate("MainWindow", "Select All"))
        self.clearAllMeasuredButton.setText(_translate("MainWindow", "Clear All"))
        self.measuredMagnitudeCurvesLabel.setText(_translate("MainWindow", "Curves"))
        self.graphTabs.setTabText(self.graphTabs.indexOf(self.measuredMagnitudeTab), _translate("MainWindow", "Measured - Magnitude"))
        self.graphTabs.setTabText(self.graphTabs.indexOf(self.measuredPolarTab), _translate("MainWindow", "Measured - Polar"))
        self.graphTabs.setTabText(self.graphTabs.indexOf(self.measuredMultiTab), _translate("MainWindow", "Measured - Multi"))
        self.selectAllModalParametersButton.setText(_translate("MainWindow", "Select All"))
        self.clearAllModalParametersButton.setText(_translate("MainWindow", "Clear All"))
        self.modesLabel.setText(_translate("MainWindow", "Modes"))
        self.graphTabs.setTabText(self.graphTabs.indexOf(self.modalParametersTab), _translate("MainWindow", "Modal - Parameters"))
        self.graphTabs.setTabText(self.graphTabs.indexOf(self.modalPolarTab), _translate("MainWindow", "Modal - Polar"))
        self.graphTabs.setTabText(self.graphTabs.indexOf(self.modalMultiTab), _translate("MainWindow", "Modal - Multi"))
        self.menuFile.setTitle(_translate("MainWindow", "&File"))
        self.menuHelp.setTitle(_translate("MainWindow", "&Help"))
        self.menuSettings.setTitle(_translate("MainWindow", "&Settings"))
        self.actionLoad.setText(_translate("MainWindow", "&Load"))
        self.actionLoad.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSave_Current_Image.setText(_translate("MainWindow", "Save &Chart"))
        self.actionSave_Current_Image.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionShow_Logs.setText(_translate("MainWindow", "Show &Logs"))
        self.actionShow_Logs.setShortcut(_translate("MainWindow", "Ctrl+L"))
        self.actionModal_Parameters.setText(_translate("MainWindow", "&Modal Parameters"))
        self.actionModal_Parameters.setShortcut(_translate("MainWindow", "Ctrl+M"))
        self.actionAbout.setText(_translate("MainWindow", "&About"))
        self.action_Display.setText(_translate("MainWindow", "&Display"))
        self.action_Display.setShortcut(_translate("MainWindow", "Ctrl+D"))

from app import MplWidget
