# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pypolarmap.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1638, 793)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.graphTabs = QtWidgets.QTabWidget(self.centralwidget)
        self.graphTabs.setEnabled(False)
        self.graphTabs.setMinimumSize(QtCore.QSize(0, 0))
        self.graphTabs.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.graphTabs.setObjectName("graphTabs")
        self.measuredMagnitudeTab = QtWidgets.QWidget()
        self.measuredMagnitudeTab.setObjectName("measuredMagnitudeTab")
        self.measuredMagnitudeGridLayout = QtWidgets.QGridLayout(self.measuredMagnitudeTab)
        self.measuredMagnitudeGridLayout.setObjectName("measuredMagnitudeGridLayout")
        self.measuredMagnitudeControlLayout = QtWidgets.QGridLayout()
        self.measuredMagnitudeControlLayout.setObjectName("measuredMagnitudeControlLayout")
        self.selectAllMeasuredButton = QtWidgets.QPushButton(self.measuredMagnitudeTab)
        self.selectAllMeasuredButton.setObjectName("selectAllMeasuredButton")
        self.measuredMagnitudeControlLayout.addWidget(self.selectAllMeasuredButton, 1, 0, 1, 1)
        self.clearAllMeasuredButton = QtWidgets.QPushButton(self.measuredMagnitudeTab)
        self.clearAllMeasuredButton.setObjectName("clearAllMeasuredButton")
        self.measuredMagnitudeControlLayout.addWidget(self.clearAllMeasuredButton, 1, 1, 1, 1)
        self.measuredMagnitudeCurves = QtWidgets.QListWidget(self.measuredMagnitudeTab)
        self.measuredMagnitudeCurves.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.measuredMagnitudeCurves.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.measuredMagnitudeCurves.setObjectName("measuredMagnitudeCurves")
        self.measuredMagnitudeControlLayout.addWidget(self.measuredMagnitudeCurves, 2, 0, 1, 2)
        self.measuredMagnitudeCurvesLabel = QtWidgets.QLabel(self.measuredMagnitudeTab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.measuredMagnitudeCurvesLabel.setFont(font)
        self.measuredMagnitudeCurvesLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.measuredMagnitudeCurvesLabel.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.measuredMagnitudeCurvesLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.measuredMagnitudeCurvesLabel.setObjectName("measuredMagnitudeCurvesLabel")
        self.measuredMagnitudeControlLayout.addWidget(self.measuredMagnitudeCurvesLabel, 0, 0, 1, 2)
        self.measuredMagnitudeGridLayout.addLayout(self.measuredMagnitudeControlLayout, 0, 0, 1, 1)
        self.measuredMagnitudeGraph = MplWidget(self.measuredMagnitudeTab)
        self.measuredMagnitudeGraph.setMinimumSize(QtCore.QSize(847, 400))
        self.measuredMagnitudeGraph.setObjectName("measuredMagnitudeGraph")
        self.measuredMagnitudeGridLayout.addWidget(self.measuredMagnitudeGraph, 0, 1, 1, 1)
        self.measuredMagnitudeGridLayout.setColumnStretch(1, 1)
        self.graphTabs.addTab(self.measuredMagnitudeTab, "")
        self.measuredPolarTab = QtWidgets.QWidget()
        self.measuredPolarTab.setObjectName("measuredPolarTab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.measuredPolarTab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.measuredPolarGraph = MplWidget(self.measuredPolarTab)
        self.measuredPolarGraph.setMinimumSize(QtCore.QSize(847, 400))
        self.measuredPolarGraph.setObjectName("measuredPolarGraph")
        self.gridLayout_4.addWidget(self.measuredPolarGraph, 0, 0, 1, 1)
        self.graphTabs.addTab(self.measuredPolarTab, "")
        self.measuredMultiTab = QtWidgets.QWidget()
        self.measuredMultiTab.setObjectName("measuredMultiTab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.measuredMultiTab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.measuredMultiGraph = MplWidget(self.measuredMultiTab)
        self.measuredMultiGraph.setMinimumSize(QtCore.QSize(847, 400))
        self.measuredMultiGraph.setObjectName("measuredMultiGraph")
        self.gridLayout_5.addWidget(self.measuredMultiGraph, 0, 0, 1, 1)
        self.graphTabs.addTab(self.measuredMultiTab, "")
        self.gridLayout.addWidget(self.graphTabs, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1638, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoad = QtWidgets.QAction(MainWindow)
        self.actionLoad.setObjectName("actionLoad")
        self.actionSave_Current_Image = QtWidgets.QAction(MainWindow)
        self.actionSave_Current_Image.setObjectName("actionSave_Current_Image")
        self.actionShow_Logs = QtWidgets.QAction(MainWindow)
        self.actionShow_Logs.setObjectName("actionShow_Logs")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.action_Display = QtWidgets.QAction(MainWindow)
        self.action_Display.setObjectName("action_Display")
        self.menuFile.addAction(self.actionLoad)
        self.menuFile.addAction(self.actionSave_Current_Image)
        self.menuHelp.addAction(self.actionShow_Logs)
        self.menuHelp.addAction(self.actionAbout)
        self.menuSettings.addAction(self.action_Display)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.graphTabs.setCurrentIndex(0)
        self.selectAllMeasuredButton.clicked.connect(self.measuredMagnitudeCurves.selectAll)
        self.graphTabs.currentChanged['int'].connect(MainWindow.onGraphTabChange)
        self.clearAllMeasuredButton.clicked.connect(self.measuredMagnitudeCurves.clearSelection)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "pypolarmap"))
        self.selectAllMeasuredButton.setText(_translate("MainWindow", "Select All"))
        self.clearAllMeasuredButton.setText(_translate("MainWindow", "Clear All"))
        self.measuredMagnitudeCurvesLabel.setText(_translate("MainWindow", "Curves"))
        self.graphTabs.setTabText(self.graphTabs.indexOf(self.measuredMagnitudeTab), _translate("MainWindow", "Measured - Magnitude"))
        self.graphTabs.setTabText(self.graphTabs.indexOf(self.measuredPolarTab), _translate("MainWindow", "Measured - Polar"))
        self.graphTabs.setTabText(self.graphTabs.indexOf(self.measuredMultiTab), _translate("MainWindow", "Measured - Multi"))
        self.menuFile.setTitle(_translate("MainWindow", "&File"))
        self.menuHelp.setTitle(_translate("MainWindow", "&Help"))
        self.menuSettings.setTitle(_translate("MainWindow", "&Settings"))
        self.actionLoad.setText(_translate("MainWindow", "&Load"))
        self.actionLoad.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSave_Current_Image.setText(_translate("MainWindow", "Save &Chart"))
        self.actionSave_Current_Image.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionShow_Logs.setText(_translate("MainWindow", "Show &Logs"))
        self.actionShow_Logs.setShortcut(_translate("MainWindow", "Ctrl+L"))
        self.actionAbout.setText(_translate("MainWindow", "&About"))
        self.action_Display.setText(_translate("MainWindow", "&Display"))
        self.action_Display.setShortcut(_translate("MainWindow", "Ctrl+D"))
from app import MplWidget
